package webutil

import "net/http"

const (
	StatusBadRequest                   = HttpError(http.StatusBadRequest)
	StatusUnauthorized                 = HttpError(http.StatusUnauthorized)
	StatusPaymentRequired              = HttpError(http.StatusPaymentRequired)
	StatusForbidden                    = HttpError(http.StatusForbidden)
	StatusNotFound                     = HttpError(http.StatusNotFound)
	StatusMethodNotAllowed             = HttpError(http.StatusMethodNotAllowed)
	StatusNotAcceptable                = HttpError(http.StatusNotAcceptable)
	StatusProxyAuthRequired            = HttpError(http.StatusProxyAuthRequired)
	StatusRequestTimeout               = HttpError(http.StatusRequestTimeout)
	StatusConflict                     = HttpError(http.StatusConflict)
	StatusGone                         = HttpError(http.StatusGone)
	StatusLengthRequired               = HttpError(http.StatusLengthRequired)
	StatusPreconditionFailed           = HttpError(http.StatusPreconditionFailed)
	StatusRequestEntityTooLarge        = HttpError(http.StatusRequestEntityTooLarge)
	StatusRequestURITooLong            = HttpError(http.StatusRequestURITooLong)
	StatusUnsupportedMediaType         = HttpError(http.StatusUnsupportedMediaType)
	StatusRequestedRangeNotSatisfiable = HttpError(http.StatusRequestedRangeNotSatisfiable)
	StatusExpectationFailed            = HttpError(http.StatusExpectationFailed)
	StatusTeapot                       = HttpError(http.StatusTeapot)
	StatusMisdirectedRequest           = HttpError(http.StatusMisdirectedRequest)
	StatusUnprocessableEntity          = HttpError(http.StatusUnprocessableEntity)
	StatusLocked                       = HttpError(http.StatusLocked)
	StatusFailedDependency             = HttpError(http.StatusFailedDependency)
	StatusTooEarly                     = HttpError(http.StatusTooEarly)
	StatusUpgradeRequired              = HttpError(http.StatusUpgradeRequired)
	StatusPreconditionRequired         = HttpError(http.StatusPreconditionRequired)
	StatusTooManyRequests              = HttpError(http.StatusTooManyRequests)
	StatusRequestHeaderFieldsTooLarge  = HttpError(http.StatusRequestHeaderFieldsTooLarge)
	StatusUnavailableForLegalReasons   = HttpError(http.StatusUnavailableForLegalReasons)

	StatusInternalServerError           = HttpError(http.StatusInternalServerError)
	StatusNotImplemented                = HttpError(http.StatusNotImplemented)
	StatusBadGateway                    = HttpError(http.StatusBadGateway)
	StatusServiceUnavailable            = HttpError(http.StatusServiceUnavailable)
	StatusGatewayTimeout                = HttpError(http.StatusGatewayTimeout)
	StatusHTTPVersionNotSupported       = HttpError(http.StatusHTTPVersionNotSupported)
	StatusVariantAlsoNegotiates         = HttpError(http.StatusVariantAlsoNegotiates)
	StatusInsufficientStorage           = HttpError(http.StatusInsufficientStorage)
	StatusLoopDetected                  = HttpError(http.StatusLoopDetected)
	StatusNotExtended                   = HttpError(http.StatusNotExtended)
	StatusNetworkAuthenticationRequired = HttpError(http.StatusNetworkAuthenticationRequired)
)
